<%= constant.warning %>

version: '2'

services:
  api-doc:
    restart: always
    image: swaggerapi/swagger-ui
    container_name: fju-health-api-doc
    environment:
      - API_URL=<%= apiDocUrl %>
    ports:
      - "8080:8080"
    volumes:
      - ../../:/usr/src/app

  db:
    restart: always
    image: fju-health-db
    container_name: fju-health-db
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      - POSTGRES_USER=<%= db.user %>
      - POSTGRES_PASSWORD=<%= db.password %>
      - POSTGRES_DB=<%= db.database %>
    ports:
      - "<%= db.port %>:5432"

  redis:
    restart: always
    image: fju-io-redis
    container_name: fju-io-redis
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "<%= redis.port %>:6379"